apiVersion: v1
kind: Service
metadata:
  name: my-spring-boot-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 32321
  #      targetPort: 8080 # not working
  selector:
    app: my-spring-boot-app
